export const track = {
  title: "Gold",
  artiste: "Loi",
  src: require("./assets/Loi - Gold.mp3"),
  artwork: "",
  lyrics: [
    {
      time: "00:06.23",
      line: "The sun leaves, and I'm waving goodbye, but these",
    },
    {
      time: "00:09.47",
      line: "Street lights, they still shining bright, lately",
    },
    { time: "00:12.59", line: "I was getting kinda used to the dark" },
    {
      time: "00:15.16",
      line: "But it never got too close to my heart (eh, ayy)",
    },
    {
      time: "00:19.08",
      line: "But then I saw you walk through the room, and your",
    },
    {
      time: "00:22.04",
      line: "Sweet eyes, they were shining through every",
    },
    { time: "00:24.95", line: "Little corner 'til our eyes would meet" },
    { time: "00:27.77", line: "And suddenly it's all I can see-e-e" },
    { time: "00:31.27", line: "All these complications" },
    { time: "00:33.71", line: "Lonely isolations" },
    { time: "00:36.92", line: "I can see them fade away" },
    { time: "00:42.86", line: "I can feel the sunshine in my life" },
    { time: "00:45.56", line: "I'm just a little happier by your side" },
    { time: "00:48.85", line: "Hold my hand when I need you the most" },
    { time: "00:52.06", line: "It's your love that is weighted in gold" },
    { time: "00:55.00", line: "I can feel the sunshine in my life" },
    { time: "00:58.20", line: "I'm just a little happier by your side" },
    { time: "01:01.61", line: "Hold my hand when I need you the most" },
    {
      time: "01:04.08",
      line: "It's your love that is weighted in gold, weighted in gold",
    },
    { time: "01:07.20", line: "Weighted in gold" },
    {
      time: "01:19.99",
      line: "It's your love that is weighted in gold, weighted in gold",
    },
    { time: "01:20.81", line: "I'm done, I'm ready for change, I got" },
    {
      time: "01:23.35",
      line: "New shoes and a smile on my face 'cause I'm",
    },
    {
      time: "01:26.26",
      line: "Walking on the sunny side, now I'll never leave",
    },
    { time: "01:29.52", line: "Finally, I start to bre-e-eathe" },
    { time: "01:32.80", line: "All these complications" },
    { time: "01:35.62", line: "Lonely isolations" },
    { time: "01:38.96", line: "I can see them fade away" },
    { time: "01:42.31", line: "I can feel the sunshine in my life" },
    { time: "01:47.87", line: "I'm just a little happier by your side" },
    { time: "01:51.50", line: "Hold my hand when I need you the most" },
    { time: "01:54.77", line: "It's your love that is weighted in gold" },
    { time: "01:56.82", line: "I can feel the sunshine in my life" },
    { time: "01:59.85", line: "I'm just a little happier by your side" },
    { time: "02:03.41", line: "Hold my hand when I need you the most" },
    {
      time: "02:06.45",
      line: "It's your love that is weighted in gold, weighted in gold, oh, whoa",
    },
    { time: "02:09.34", line: "Weighted in gold" },
    {
      time: "02:18.80",
      line: "It's your love that is weighted in gold, weighted in gold",
    },
    {
      time: "02:21.49",
      line: "Weighted in gold, weighted in gold, weighted in gold",
    },
    { time: "02:31.28", line: "It's your love that is weighted in gold" },
    { time: "02:34.04", line: "I can feel the sunshine in my life" },
    { time: "02:37.10", line: "I'm just a little happier by your side" },
    { time: "02:41.15", line: "Hold my hand when I need you the most" },
    {
      time: "02:44.22",
      line: "It's your love that is weighted in gold, weighted in gold",
    },
  ],
};
